analyzer:
  errors:
    flutter_style_todos: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    avoid_print: false
    always_use_package_imports: false
