name: usda_db_package
description: A package to json-ize the usda db.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  # freezed: ^2.4.1
  # freezed_annotation: ^2.4.1



dev_dependencies:
  build_runner: ^2.4.6
  # flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - lib/data/
