name: usda_db_package
description: A package to json-ize the usda db.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  mocktail: ^1.0.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - lib/data/
