name: usda_db
description: A package to json-ize dth usda db.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  # get_it: ^7.6.4
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
