/// Thrown when the database cannot be initialized, or when it is queried
/// before `UsdaDbDAO.init` has completed successfully.
class DBException implements Exception {
  /// Creates a [DBException] describing [errorMessage], carrying [stackTrace]
  /// from the underlying error where there was one.
  DBException(this.errorMessage, [this.stackTrace]);

  /// Description of what went wrong.
  final String errorMessage;

  /// Stack trace of the underlying error, where one was available.
  final StackTrace? stackTrace;

  @override
  String toString() {
    return 'DBException: $errorMessage\nStack Trace: $stackTrace';
  }
}

/// Thrown when one of the packaged data files can be read but not decoded.
///
/// Usually means the data file is truncated, or was generated by a version of
/// the generator that wrote a shape this package no longer understands. The
/// message carries the underlying decode error.
class DBFormatException implements Exception {
  /// Creates a [DBFormatException] describing [errorMessage], carrying
  /// [stackTrace] from the underlying decode error where there was one.
  DBFormatException(this.errorMessage, [this.stackTrace]);

  /// Description of what went wrong, including the underlying decode error.
  final String errorMessage;

  /// Stack trace of the underlying error, where one was available.
  final StackTrace? stackTrace;

  @override
  String toString() {
    return 'DBFormatException: $errorMessage\nStack Trace: $stackTrace';
  }
}

/// Thrown when one of the packaged data assets cannot be read.
///
/// Usually means the asset bundle is missing a data file, most often because
/// the consuming app has not picked up this package's assets, or because the
/// hash in `file_manifest.txt` no longer matches the data file names.
class DBFileException implements Exception {
  /// Creates a [DBFileException] describing [errorMessage], carrying
  /// [stackTrace] from the underlying bundle error where there was one.
  DBFileException(this.errorMessage, [this.stackTrace]);

  /// Description of what went wrong, including the asset path attempted.
  final String errorMessage;

  /// Stack trace of the underlying error, where one was available.
  final StackTrace? stackTrace;

  @override
  String toString() {
    return 'DBFileException: $errorMessage\nStack Trace: $stackTrace';
  }
}
