/// Thrown when the database cannot be initialized, or when it is queried
/// before `UsdaDb.init` has completed successfully.
class UsdaDbException implements Exception {
  /// Creates a [UsdaDbException] describing [errorMessage], carrying [stackTrace]
  /// from the underlying error where there was one.
  UsdaDbException(this.errorMessage, [this.stackTrace]);

  /// Description of what went wrong.
  final String errorMessage;

  /// Stack trace of the underlying error, where one was available.
  final StackTrace? stackTrace;

  @override
  String toString() {
    return 'UsdaDbException: $errorMessage\nStack Trace: $stackTrace';
  }
}

/// Thrown when one of the packaged data files can be read but not decoded.
///
/// Usually means the data file is truncated, or was generated by a version of
/// the generator that wrote a shape this package no longer understands. The
/// message carries the underlying decode error.
class UsdaDbFormatException implements Exception {
  /// Creates a [UsdaDbFormatException] describing [errorMessage], carrying
  /// [stackTrace] from the underlying decode error where there was one.
  UsdaDbFormatException(this.errorMessage, [this.stackTrace]);

  /// Description of what went wrong, including the underlying decode error.
  final String errorMessage;

  /// Stack trace of the underlying error, where one was available.
  final StackTrace? stackTrace;

  @override
  String toString() {
    return 'UsdaDbFormatException: $errorMessage\nStack Trace: $stackTrace';
  }
}

/// Thrown when one of the packaged data assets cannot be read.
///
/// Usually means the asset bundle is missing a data file, most often because
/// the consuming app has not picked up this package's assets, or because the
/// hash in `file_manifest.txt` no longer matches the data file names.
class UsdaDbFileException implements Exception {
  /// Creates a [UsdaDbFileException] describing [errorMessage], carrying
  /// [stackTrace] from the underlying bundle error where there was one.
  UsdaDbFileException(this.errorMessage, [this.stackTrace]);

  /// Description of what went wrong, including the asset path attempted.
  final String errorMessage;

  /// Stack trace of the underlying error, where one was available.
  final StackTrace? stackTrace;

  @override
  String toString() {
    return 'UsdaDbFileException: $errorMessage\nStack Trace: $stackTrace';
  }
}
